services:
  - type: web
    name: pattradhara-dev
    runtime: python
    buildCommand: ./render-build.sh
    startCommand: python backend/server.py
    envVars:
      - key: DB_NAME
        value: portfolio_prod
      - key: CORS_ORIGINS
        value: https://pattradhara-dev.onrender.com
