services:
  - type: web
    name: pattradhara-dev
    runtime: python
    buildCommand: ./render-build.sh
    startCommand: uvicorn backend.server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DB_NAME
        value: portfolio_prod
      - key: CORS_ORIGINS
        value: https://pattradhara-dev-frontend.onrender.com

  - type: web
    name: pattradhara-dev-frontend
    runtime: static
    buildCommand: cd frontend && yarn install && yarn build
    staticPublishPath: frontend/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
